name: guardian_angel
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  persistent_bottom_nav_bar: ^5.0.2
  cupertino_icons: ^1.0.2
  fluster: ^1.2.0
  flutter_cache_manager: ^3.3.1
  camera: ^0.10.4
  image_picker: ^0.8.7+4
  permission_handler: ^11.0.1
  awesome_dialog: ^3.0.2
  google_maps_flutter: ^2.7.0
  custom_map_markers: ^0.0.2+1
  flutter_polyline_points: ^2.0.0
  pinput: ^2.2.31
  animated_custom_dropdown: any
  # speech_to_text: ^6.6.0
  flutter_background_geolocation: ^4.13.7
  geolocator: ^11.0.0
  provider: ^6.1.1
  latlng: any
  fluttertoast: any
  onesignal_flutter: ^5.1.0
  mqtt_client: ^10.2.1
  translator: ^1.0.0
  shared_preferences: ^2.2.3
  get_it: ^7.7.0
  intl: any
  firebase_core: any
  firebase_auth: any
  firebase_phone_auth_handler: any
  file_picker: any
  async_builder: ^1.2.0
  cached_network_image: ^3.3.1
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/dogs/
    - assets/icons/
    - assets/icons/validator/
    - assets/images/category/
    - assets/markers/
    - assets/icons/selected/
    - assets/icons/unselected/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins_Light.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins_Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins_Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins_SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins_Bold.ttf
          weight: 900
